import type { CoachSeat, ItineraryItem, Pilgrim, Room, Trip } from "./types";

export const trips: Trip[] = [
  {
    id: "lourdes-2026",
    code: "LRD-2609",
    title: "Lourdes · Settembre 2026",
    destination: "Lourdes, Francia",
    startDate: "2026-09-10",
    endDate: "2026-09-14",
    status: "Aperto",
    participants: 126,
    capacity: 140,
    revenue: 119700,
    collected: 87640,
    hotels: 2,
    coaches: 3,
    walkingKm: 18,
    leader: "Elena Bianchi",
    coverTone: "blue",
    checklist: { documents: 14, rooms: 6, seats: 3, balances: 23 },
  },
  {
    id: "fatima-2026",
    code: "FTM-2610",
    title: "Fatima e Lisbona",
    destination: "Fatima, Portogallo",
    startDate: "2026-10-03",
    endDate: "2026-10-08",
    status: "Confermato",
    participants: 78,
    capacity: 82,
    revenue: 94380,
    collected: 81200,
    hotels: 2,
    coaches: 2,
    walkingKm: 12,
    leader: "Marco Neri",
    coverTone: "amber",
    checklist: { documents: 5, rooms: 2, seats: 0, balances: 9 },
  },
  {
    id: "roma-2027",
    code: "ROM-2703",
    title: "Roma · Giubileo dei gruppi",
    destination: "Roma, Italia",
    startDate: "2027-03-18",
    endDate: "2027-03-21",
    status: "Bozza",
    participants: 34,
    capacity: 100,
    revenue: 23800,
    collected: 6800,
    hotels: 1,
    coaches: 2,
    walkingKm: 22,
    leader: "Da assegnare",
    coverTone: "violet",
    checklist: { documents: 18, rooms: 34, seats: 34, balances: 28 },
  },
  {
    id: "santiago-2027",
    code: "SCQ-2705",
    title: "Cammino di Santiago",
    destination: "Galizia, Spagna",
    startDate: "2027-05-09",
    endDate: "2027-05-17",
    status: "Aperto",
    participants: 29,
    capacity: 36,
    revenue: 49300,
    collected: 26100,
    hotels: 7,
    coaches: 1,
    walkingKm: 112,
    leader: "Lucia Ferri",
    coverTone: "teal",
    checklist: { documents: 7, rooms: 8, seats: 2, balances: 18 },
  },
];

export const pilgrims: Pilgrim[] = [
  {
    id: "p-001",
    initials: "AR",
    name: "Anna Rossi",
    email: "anna.rossi@example.it",
    phone: "+39 333 120 4498",
    birthDate: "1958-04-12",
    city: "Bologna",
    group: "Parrocchia San Luca",
    tripId: "lourdes-2026",
    tripName: "Lourdes · Settembre 2026",
    status: "Confermato",
    paymentStatus: "Parziale",
    paid: 500,
    total: 950,
    room: "Hotel Alba · 204",
    coachSeat: "Pullman 1 · 12A",
    dietary: ["Senza glutine"],
    mobility: "Supporto leggero",
    walkingKm: 4,
    missingItems: ["Saldo"],
    emergencyContact: "Paolo Rossi · +39 333 555 0192",
    documentExpiry: "2028-10-04",
  },
  {
    id: "p-002",
    initials: "GM",
    name: "Giuseppe Marino",
    email: "g.marino@example.it",
    phone: "+39 347 881 2204",
    birthDate: "1949-11-23",
    city: "Modena",
    group: "Unitalsi Modena",
    tripId: "lourdes-2026",
    tripName: "Lourdes · Settembre 2026",
    status: "Da completare",
    paymentStatus: "Scaduto",
    paid: 250,
    total: 950,
    room: null,
    coachSeat: "Pullman 1 · 03B",
    dietary: ["Diabete", "Pasto iposodico"],
    mobility: "Assistenza",
    walkingKm: 1,
    missingItems: ["Documento", "Camera", "Saldo"],
    emergencyContact: "Maria Marino · +39 320 990 1234",
    documentExpiry: "2026-08-21",
  },
  {
    id: "p-003",
    initials: "CB",
    name: "Carla Bianchi",
    email: "carla.b@example.it",
    phone: "+39 338 661 4201",
    birthDate: "1964-02-05",
    city: "Firenze",
    group: "Parrocchia Santa Croce",
    tripId: "lourdes-2026",
    tripName: "Lourdes · Settembre 2026",
    status: "Confermato",
    paymentStatus: "Pagato",
    paid: 1040,
    total: 1040,
    room: "Hotel Alba · 301",
    coachSeat: "Pullman 2 · 08A",
    dietary: ["Vegetariano"],
    mobility: "Autonomo",
    walkingKm: 12,
    missingItems: [],
    emergencyContact: "Luca Bianchi · +39 335 124 7712",
    documentExpiry: "2030-05-17",
  },
  {
    id: "p-004",
    initials: "LP",
    name: "Luigi Parisi",
    email: "luigi.parisi@example.it",
    phone: "+39 329 004 8103",
    birthDate: "1955-08-19",
    city: "Prato",
    group: "Parrocchia Santa Croce",
    tripId: "lourdes-2026",
    tripName: "Lourdes · Settembre 2026",
    status: "In attesa",
    paymentStatus: "Parziale",
    paid: 300,
    total: 950,
    room: "Hotel Alba · 305",
    coachSeat: null,
    dietary: [],
    mobility: "Autonomo",
    walkingKm: 8,
    missingItems: ["Posto pullman", "Saldo"],
    emergencyContact: "Laura Parisi · +39 333 892 4451",
    documentExpiry: "2029-01-09",
  },
  {
    id: "p-005",
    initials: "ES",
    name: "Elisa Serra",
    email: "e.serra@example.it",
    phone: "+39 335 771 9042",
    birthDate: "1971-06-30",
    city: "Ferrara",
    group: "Gruppo San Giorgio",
    tripId: "fatima-2026",
    tripName: "Fatima e Lisbona",
    status: "Confermato",
    paymentStatus: "Pagato",
    paid: 1210,
    total: 1210,
    room: "Hotel Luz · 118",
    coachSeat: "Pullman 1 · 15C",
    dietary: ["Allergia alle arachidi"],
    mobility: "Autonomo",
    walkingKm: 15,
    missingItems: [],
    emergencyContact: "Giorgio Serra · +39 338 112 7740",
    documentExpiry: "2027-12-22",
  },
  {
    id: "p-006",
    initials: "MF",
    name: "Mario Fontana",
    email: "mario.fontana@example.it",
    phone: "+39 349 241 0309",
    birthDate: "1947-03-15",
    city: "Ravenna",
    group: "Gruppo San Giorgio",
    tripId: "fatima-2026",
    tripName: "Fatima e Lisbona",
    status: "Da completare",
    paymentStatus: "Da pagare",
    paid: 0,
    total: 1210,
    room: null,
    coachSeat: null,
    dietary: ["Intolleranza al lattosio"],
    mobility: "Supporto leggero",
    walkingKm: 3,
    missingItems: ["Acconto", "Camera", "Posto pullman"],
    emergencyContact: "Franca Fontana · +39 338 410 2240",
    documentExpiry: "2026-11-02",
  },
  {
    id: "p-007",
    initials: "DG",
    name: "Daniela Gori",
    email: "daniela.gori@example.it",
    phone: "+39 340 991 3308",
    birthDate: "1982-09-08",
    city: "Roma",
    group: "Cammini Aperti",
    tripId: "santiago-2027",
    tripName: "Cammino di Santiago",
    status: "Confermato",
    paymentStatus: "Parziale",
    paid: 600,
    total: 1700,
    room: "Pensión Norte · 12",
    coachSeat: "Minibus · 04",
    dietary: ["Vegano"],
    mobility: "Autonomo",
    walkingKm: 28,
    missingItems: ["Saldo"],
    emergencyContact: "Stefano Gori · +39 340 121 2910",
    documentExpiry: "2031-06-12",
  },
  {
    id: "p-008",
    initials: "RT",
    name: "Roberto Testa",
    email: "roberto.t@example.it",
    phone: "+39 333 442 7600",
    birthDate: "1977-12-01",
    city: "Milano",
    group: "Cammini Aperti",
    tripId: "santiago-2027",
    tripName: "Cammino di Santiago",
    status: "In attesa",
    paymentStatus: "Da pagare",
    paid: 0,
    total: 1700,
    room: null,
    coachSeat: null,
    dietary: [],
    mobility: "Autonomo",
    walkingKm: 20,
    missingItems: ["Acconto", "Certificato cammino"],
    emergencyContact: "Sara Testa · +39 333 942 1180",
    documentExpiry: "2029-03-18",
  },
];

export const rooms: Room[] = [
  { id: "r-201", number: "201", type: "Doppia", capacity: 2, guests: ["Anna Rossi", "Maria Conti"], floor: 2 },
  { id: "r-202", number: "202", type: "Tripla", capacity: 3, guests: ["Franca Villa", "Elena Neri"], floor: 2 },
  { id: "r-203", number: "203", type: "Accessibile", capacity: 2, guests: ["Giuseppe Marino"], floor: 2 },
  { id: "r-204", number: "204", type: "Doppia", capacity: 2, guests: ["Luigi Parisi"], floor: 2 },
  { id: "r-301", number: "301", type: "Singola", capacity: 1, guests: ["Carla Bianchi"], floor: 3 },
  { id: "r-302", number: "302", type: "Doppia", capacity: 2, guests: [], floor: 3 },
];

export const itinerary: ItineraryItem[] = [
  { time: "06:30", title: "Ritrovo e check-in", detail: "Piazzale della parrocchia · Pullman 1, 2 e 3", type: "travel" },
  { time: "07:15", title: "Partenza", detail: "Prima sosta prevista alle 10:15", type: "travel" },
  { time: "12:30", title: "Pranzo libero", detail: "Area di servizio Montélimar", type: "meal" },
  { time: "18:20", title: "Arrivo a Lourdes", detail: "Distribuzione chiavi Hotel Alba e Hotel Miramont", type: "hotel" },
  { time: "20:00", title: "Cena dei gruppi", detail: "Segnalare 11 menu speciali", type: "meal" },
  { time: "21:30", title: "Fiaccolata mariana", detail: "Percorso 2,4 km · alternativa accessibile disponibile", type: "walk" },
];

export const coachSeats: CoachSeat[] = Array.from({ length: 32 }, (_, index) => {
  const number = `${Math.floor(index / 4) + 1}${["A", "B", "C", "D"][index % 4]}`;
  const assignments: Record<string, string> = {
    "1A": "Elena Bianchi",
    "1B": "Don Marco",
    "3B": "Giuseppe Marino",
    "8A": "Carla Bianchi",
    "12A": "Anna Rossi",
    "15C": "Elisa Serra",
  };
  return {
    number,
    passenger: assignments[number] ?? null,
    reserved: number === "1A" || number === "1B",
    accessibility: number === "3A" || number === "3B",
  };
});
