"use client";

import { ChevronLeft, Save, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";
import { updatePilgrimAction } from "@/app/actions";
import type { PilgrimEditData } from "@/lib/edit-data";

export function PilgrimEditForm({ data }: { data: PilgrimEditData }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const result = await updatePilgrimAction(new FormData(event.currentTarget)); setBusy(false); if (!result.ok) { setError(result.message); return; } router.push(`/pellegrini/${data.id}`); router.refresh(); }
  return <form className="editor-layout" method="post" onSubmit={submit}><aside className="editor-steps"><Link href={`/pellegrini/${data.id}`}><ChevronLeft size={15} /> Torna alla scheda</Link><p className="nav-label">Modifica pellegrino</p><div className="security-note"><ShieldCheck size={18} /><p><strong>Dati protetti</strong>Le informazioni sanitarie restano separate e soggette a RLS.</p></div></aside><div className="editor-main"><div className="editor-heading"><div><p className="eyebrow">Anagrafica</p><h1>Modifica pellegrino</h1><p>Aggiorna dati personali, contatti ed esigenze operative.</p></div></div>{error ? <div className="form-error form-error-block">{error}</div> : null}<input type="hidden" name="pilgrimId" value={data.id} /><input type="hidden" name="privacyDelivered" value="on" /><input type="hidden" name="tripId" value="" /><input type="hidden" name="groupName" value="" /><input type="hidden" name="roomPreference" value="" /><input type="hidden" name="roommate" value="" /><input type="hidden" name="privacyNoticeVersion" value="v1" />
    <section className="form-card"><div className="form-card-title"><span>01</span><div><h2>Dati personali</h2></div></div><div className="form-grid"><label><span>Nome *</span><input name="firstName" defaultValue={data.firstName} required /></label><label><span>Cognome *</span><input name="lastName" defaultValue={data.lastName} required /></label><label><span>Data di nascita *</span><input name="birthDate" type="date" defaultValue={data.birthDate} required /></label><label><span>Codice fiscale</span><input name="fiscalCode" defaultValue={data.fiscalCode} /></label><label><span>Luogo di nascita</span><input name="birthPlace" defaultValue={data.birthPlace} /></label><label><span>Nazionalità *</span><input name="nationality" defaultValue={data.nationality} required /></label></div></section>
    <section className="form-card"><div className="form-card-title"><span>02</span><div><h2>Contatti</h2></div></div><div className="form-grid"><label><span>Email</span><input name="email" type="email" defaultValue={data.email} /></label><label><span>Telefono *</span><input name="phone" defaultValue={data.phone} required /></label><label><span>Indirizzo</span><input name="address" defaultValue={data.address} /></label><label><span>Città</span><input name="city" defaultValue={data.city} /></label><label><span>Contatto emergenza *</span><input name="emergencyName" defaultValue={data.emergencyName} required /></label><label><span>Telefono emergenza *</span><input name="emergencyPhone" defaultValue={data.emergencyPhone} required /></label></div></section>
    <section className="form-card sensitive-card"><div className="form-card-title"><span>03</span><div><h2>Esigenze e assistenza</h2></div></div><div className="form-grid"><label><span>Mobilità</span><select name="mobility" defaultValue={data.mobility}><option value="independent">Autonomo</option><option value="light_support">Supporto leggero</option><option value="assistance">Assistenza</option></select></label><label><span>Cammino massimo (km)</span><input name="walkingKm" type="number" min="0" max="100" step="0.01" defaultValue={data.walkingKm} required /></label><label><span>Preferenze alimentari</span><textarea name="dietary" defaultValue={data.dietary} rows={3} /></label><label><span>Allergie</span><textarea name="allergies" defaultValue={data.allergies} rows={3} /></label><label className="form-span-2"><span>Note riservate</span><textarea name="healthNotes" defaultValue={data.healthNotes} rows={3} /></label></div><div className="checkbox-stack"><label><input name="healthConsent" type="checkbox" defaultChecked={data.healthConsent} /><span><strong>Consenso dati relativi alla salute</strong></span></label><label><input name="operationalMessagesAllowed" type="checkbox" defaultChecked={data.operationalMessagesAllowed} /><span><strong>Comunicazioni operative autorizzate</strong></span></label></div></section>
    <div className="editor-bottom"><span>Le modifiche sensibili vengono registrate.</span><button className="button button-primary" disabled={busy} type="submit"><Save size={15} /> {busy ? "Salvataggio…" : "Salva modifiche"}</button></div></div></form>;
}
